/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author ManavEmpire
 */
public class AdminHomePage extends javax.swing.JFrame {

    public static int open = 0;
    /**
     * Creates new form AdminHomePage
     */
    public AdminHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        add_ques = new javax.swing.JMenu();
        update_ques = new javax.swing.JMenu();
        all_ques = new javax.swing.JMenu();
        del_ques = new javax.swing.JMenu();
        result = new javax.swing.JMenu();
        log_out = new javax.swing.JMenu();
        exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Navigation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 24), new java.awt.Color(51, 0, 255))); // NOI18N

        add_ques.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_ques.setText("Add New Question");
        add_ques.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add_ques.setMargin(new java.awt.Insets(0, 5, 0, 30));
        jMenuBar1.add(add_ques);

        update_ques.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_ques.setText("Update Question");
        update_ques.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        update_ques.setMargin(new java.awt.Insets(0, 5, 0, 30));
        jMenuBar1.add(update_ques);

        all_ques.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        all_ques.setText("All Questions");
        all_ques.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        all_ques.setMargin(new java.awt.Insets(0, 5, 0, 30));
        jMenuBar1.add(all_ques);

        del_ques.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        del_ques.setText("Delete Question");
        del_ques.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        del_ques.setMargin(new java.awt.Insets(0, 5, 0, 30));
        jMenuBar1.add(del_ques);

        result.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        result.setText("All Student Result");
        result.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        result.setMargin(new java.awt.Insets(0, 5, 0, 30));
        jMenuBar1.add(result);

        log_out.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        log_out.setText("Log Out");
        log_out.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        log_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log_outMouseClicked(evt);
            }
        });
        jMenuBar1.add(log_out);

        exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exit.setText("Exit");
        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void log_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_outMouseClicked
        JFrame jf = new JFrame();
        jf.setAlwaysOnTop(true);
        int a = JOptionPane.showConfirmDialog(jf,"Do you really want to log out ?","LOG OUT",JOptionPane.YES_NO_OPTION);
        
        if(a==0)
        {
            setVisible(false);
            new LoginAdmin_1().setVisible(true);
        }
        
    }//GEN-LAST:event_log_outMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        JFrame jf = new JFrame();
        jf.setAlwaysOnTop(true);
        int a = JOptionPane.showConfirmDialog(jf,"Do you really want to exit ?","EXIT",JOptionPane.YES_NO_OPTION);
        
        if(a==0)
        {
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu add_ques;
    private javax.swing.JMenu all_ques;
    private javax.swing.JMenu del_ques;
    private javax.swing.JMenu exit;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu log_out;
    private javax.swing.JMenu result;
    private javax.swing.JMenu update_ques;
    // End of variables declaration//GEN-END:variables
}
